Day1.CountCalories();
Day2.RockPaperScissors();
Day3.RucksackReorganization();
Day4.CampCleanup();
Day5.SupplyStacks();
Day6.TuningTrouble();
Day7.NoSpaceLeftOnDevice();
Day8.TreetopTreeHouse();
Day9.RopeBridge();